name: 'Display Builder Base'
description: 'Provide base start for a Display Builder website.'
type: 'Site'

# @see web/core/recipes/standard/recipe.yml
recipes:
  # From the standard profile
  - core/recipes/basic_block_type
  # Only needed because navigation.module places a shortcuts block.
  # - core/recipes/basic_shortcuts
  - core/recipes/article_comment
  - core/recipes/article_tags
  - core/recipes/article_content_type
  - core/recipes/page_content_type
  # Exclude default editor as we override them in theme recipe.
  # - core/recipes/basic_html_format_editor
  # - core/recipes/full_html_format_editor
  - core/recipes/content_search
  - core/recipes/core_recommended_performance
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_admin_theme
  # - core/recipes/core_recommended_front_end_theme
  - core/recipes/user_picture
  # Provides a fallback text format which is available to all users.
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role

  # Media recipe from core, not in standard.
  - core/recipes/audio_media_type
  - core/recipes/document_media_type
  - core/recipes/image_media_type
  - core/recipes/remote_video_media_type

  - core/recipes/standard_responsive_images/

install:
  # Core modules close to standard recipe.
  - breakpoint
  - config
  - contextual
  - datetime
  - field_ui
  - help
  - history
  - image
  - menu_link_content
  - menu_ui
  - options
  - views_ui

  # Do not use navigation as it enable layout builder.
  - toolbar

  # UI Suite.
  - ui_patterns
  - ui_patterns_field_formatters
  - ui_patterns_library
  - ui_patterns_views
  - ui_styles
  - ui_styles_ckeditor5
  - ui_styles_ui_patterns
  - ui_styles_library
  - ui_skins
  - ui_icons
  - ui_icons_field
  - ui_icons_ckeditor5
  - ui_icons_menu
  - ui_icons_library
  - ui_icons_text
  - ui_icons_patterns
  - ui_icons_media
  - ui_icons_field_link_attributes

  # Display builder.
  - display_builder
  - display_builder_entity_view
  - display_builder_page_layout
  - display_builder_views
  - display_builder_ui

  # Contrib modules recommended as minimal start for Display Builder.
  - easy_breadcrumb
  - link_attributes
  - link_attributes_menu_link_content
  - pathauto
  - redirect
  - redirect_404
  - simple_sitemap
  - sitemap
  - smart_trim
  - token

config:
  # This recipe is intended to set up a full site from scratch, fulfilling certain
  # expectations. It's not really designed to be a building block. Therefore, treat
  # all of the config strictly.
  strict: true

  import:
    # Standard recipe config without Olivero.
    claro:
      - block.block.claro_help
    help:
      - search.page.help_search
      - block.block.claro_help_search
    image:
      - image.style.large
      - image.style.thumbnail
    node:
      - views.view.archive
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
      - views.view.glossary
    user:
      - core.entity_view_mode.user.compact
      - search.page.user_search
      - views.view.user_admin_people
      - views.view.who_s_new
      - views.view.who_s_online

    # Contrib modules config.
    easy_breadcrumb: '*'
    pathauto: '*'
    redirect: '*'
    redirect_404: '*'
    simple_sitemap: '*'
    sitemap: '*'

  actions:
    # Default to standard recipe.
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    system.site:
      simpleConfigUpdate:
        page.front: /node

    user.role.anonymous:
      grantPermission: 'access content'
    user.role.authenticated:
      grantPermissions:
        - 'access content'
        - 'delete own files'
    user.role.content_editor:
      grantPermissions:
        - 'access content overview'
        - 'access contextual links'
        - 'access files overview'
        - 'access toolbar'
        - 'administer url aliases'
        - 'create terms in tags'
        - 'create url aliases'
        - 'edit own comments'
        - 'edit terms in tags'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view the administration theme'
      grantPermissionsForEachNodeType:
        - 'create %bundle content'
        - 'delete %bundle revisions'
        - 'delete own %bundle content'
        - 'edit own %bundle content'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block

    easy_breadcrumb.settings:
      simpleConfigUpdate:
        # Remove breadcrumbs when only home appears.
        # Since we print the page title, this is only the home page.
        hide_single_home_item: true

    # Exclude 404s from the log.
    redirect_404.settings:
      simpleConfigUpdate:
        suppress_404: true

    # HTML Sitemap with main menu.
    sitemap.settings:
      simpleConfigUpdate:
        page_title: Sitemap
        plugins.frontpage:
          enabled: true
          weight: 0
          settings:
            title: ''
            rss: ''
            front_text_override: ''
          id: frontpage
          provider: sitemap
        plugins.menu:main:
          enabled: true
          weight: 0
          settings:
            title: ''
            show_disabled: false
          id: 'menu:main'
          provider: sitemap
        include_css: true

    # Specific Display Builder role.
    user.role.display_builder:
      ensure_exists:
        id: display_builder
      grantPermissions:
        - 'access components page'
        - 'access ui icons library'
        - 'access_ui_styles_library'
        - 'administer display builder profile'
        - 'administer page_layout'
        - 'administer pattern preset'
        - 'use display builder advanced'
        - 'use display builder default'
        - 'use text format basic_html'
        - 'use text format full_html'
        - 'view display builder instance'
